all:
	/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool build

clean:
	rm -fr MCSwipeTableViewCellBinding/bin
	rm -fr MCSwipeTableViewCellBinding/obj
	rm -fr MCSwipeTableViewCellBinding/Resources
